language: bash node_js
dist: trusty
sudo: required

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - lib32gcc1
    - libstdc++6
    - libstdc++6:i386
    - git
    - jq
    - libevent-dev
    - libncurses-dev
    - wget
    - unzip

install:
  - npm install -g markdown-table-cli

before_script:
- git clone https://github.com/tmux/tmux.git tmux
- cd tmux
- git checkout $TMUX_VERSION
- sh autogen.sh
- ./configure --prefix=$HOME/tmux && make && make install
- export PATH=$HOME/tmux/bin:$PATH
- cd ..
- tmux -V
- wget https://ftp.pcre.org/pub/pcre/pcre2-10.32.zip
- unzip pcre2-10.32.zip
- cd pcre2-10.32
- ./configure 
- make 
- sudo make install
- sudo /sbin/ldconfig
- cd ..
- pcre2grep -V
script:
  - bash ./steamcmd_appid.sh

after_success:
  - .travis/push.sh

env:
  global:
    TMUX_VERSION: 2.6
    TMUX_SESSIONS: 3
    secure: "eygp10hkllSyXWWPdSKnc6jLQ0mIbz66QgkPTzn/aMkhckylLHbABT9msTDeJQn0dpXQYROCcvFnFBbkAxBRnFGdduP3bxMFg/7sdPziQW624jCJfIo6EmQQptzoIoe/SzQ1LDuf84yuWT5XkcxmmCIVzjJa3wmsS4lneErGnhkr0zRMMfQuTCGypj49uonuehpoIs2z6KJf20UYsxohFRv+rFg63rQItiHgyZvzThzlrI0TpOKM/QQcBk+9OevgGxsCQ7nZHv7xMtSGYpLOk/5HhNpFkrd6gJyH8ZrcRB9MKnZO/g/5SuMspVbJ4jxMIRwWhL/cPhOlrMxsdY1abZmyjvXPPXQUNgUZ91YGRb+sXkkdwNTqSL4Co72Hk6+WhKDfaFqwlTPv2ji8aF+40GlD+BjyExSeWC8A677sl5SN3iiFyEfmJki13OBim1+lSHjUX73priFGkSETrcmfXP7nxyxQ5bC/fyrG+uG3uX7lSiUUfxG0czhynbcZFI1hkTcEPtFfb2QSKGMWMLLSas8FVB/b8WbZbO4gfVXa+B9vDtTKU58ZK7i7gPu9q5+fMPj1yMITHuqe/0odFiF7XaS6Sy2FtEI6T6kVb6pjew+h+aaKchw2RtECKcHuiPd+4ooupIRE13r7ZKFtDmV/yeLiWeYHQgrQGwc9SU6xMfU=