language: bash node_js
dist: xenial
sudo: required

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - lib32gcc1
    - libstdc++6
    - libstdc++6:i386
    - git
    - jq
    - libevent-dev
    - libncurses-dev
env:
  global:
  - RETRY_TIMEOUT_SECONDS=15
  matrix:
  - TMUX_VERSION=master
  - TMUX_VERSION=2.6
  - TMUX_VERSION=2.5
  - TMUX_VERSION=2.4
  - TMUX_VERSION=2.3
  - TMUX_VERSION=2.2
  - TMUX_VERSION=2.1
  - TMUX_VERSION=2.0
  - TMUX_VERSION=1.9a
  - TMUX_VERSION=1.8
matrix:
  allow_failures:
  - env: TMUX_VERSION=master

install:
  - npm install -g markdown-table-cli

before_script:
- git clone https://github.com/tmux/tmux.git tmux
- cd tmux
- git checkout $TMUX_VERSION
- sh autogen.sh
- ./configure --prefix=$HOME/tmux && make && make install
- export PATH=$HOME/tmux/bin:$PATH
- cd ..
- tmux -V

script:
  - bash ./steamcmd_appid.sh
