language: bash node_js
dist: xenial
sudo: required

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - lib32gcc1
    - libstdc++6
    - libstdc++6:i386
    - git
    - jq

install:
  - npm install -g markdown-table-cli

script:
  - bash ./steamcmd_appid.sh
