language: bash node_js
dist: trusty
sudo: required

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - lib32gcc1
    - libstdc++6
    - libstdc++6:i386
    - git
    - jq
    - libevent-dev
    - libncurses-dev
    - pcre2-utils

install:
  - npm install -g markdown-table-cli

before_script:
- git clone https://github.com/tmux/tmux.git tmux
- cd tmux
- git checkout $TMUX_VERSION
- sh autogen.sh
- ./configure --prefix=$HOME/tmux && make && make install
- export PATH=$HOME/tmux/bin:$PATH
- cd ..
- tmux -V
script:
  - bash ./steamcmd_appid.sh

# after_success:
#   - .travis/push.sh

env:
  TMUX_VERSION: 2.6
  TMUX_SESSIONS: 4